USE [master]
GO
/****** Object:  Database [NetMapperIO]    Script Date: 05/09/2018 22:16:56 ******/
CREATE DATABASE [NetMapperIO]
GO
ALTER DATABASE [NetMapperIO] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NetMapperIO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NetMapperIO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NetMapperIO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NetMapperIO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NetMapperIO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NetMapperIO] SET ARITHABORT OFF 
GO
ALTER DATABASE [NetMapperIO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NetMapperIO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NetMapperIO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NetMapperIO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NetMapperIO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NetMapperIO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NetMapperIO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NetMapperIO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NetMapperIO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NetMapperIO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NetMapperIO] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [NetMapperIO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NetMapperIO] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [NetMapperIO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NetMapperIO] SET  MULTI_USER 
GO
ALTER DATABASE [NetMapperIO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NetMapperIO] SET ENCRYPTION ON
GO
ALTER DATABASE [NetMapperIO] SET QUERY_STORE = ON
GO
ALTER DATABASE [NetMapperIO] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO
USE [NetMapperIO]
GO
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_ADAPTIVE_JOINS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_ONLINE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_RESUMABLE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ISOLATE_SECURITY_POLICY_CARDINALITY = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZE_FOR_AD_HOC_WORKLOADS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_PROCEDURE_EXECUTION_STATISTICS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_QUERY_EXECUTION_STATISTICS = OFF;
GO
USE [NetMapperIO]
GO
/****** Object:  Table [dbo].[EdgeObjects]    Script Date: 05/09/2018 22:16:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EdgeObjects](
	[EdgeId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](32) NULL,
	[FromNodeId] [int] NOT NULL,
	[FromNodePort] [varchar](16) NOT NULL,
	[ToNodeId] [int] NOT NULL,
	[ToNodePort] [varchar](16) NOT NULL,
	[MediaTypeId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[EdgeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MediaTypes]    Script Date: 05/09/2018 22:16:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MediaTypes](
	[MediaTypeId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](64) NOT NULL,
	[Colour] [char](7) NOT NULL,
	[Dashed] [bit] NOT NULL,
	[isDefault] [bit] NOT NULL,
	[topologyId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MediaTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NetIconObjects]    Script Date: 05/09/2018 22:16:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NetIconObjects](
	[NetIconId] [int] IDENTITY(1,1) NOT NULL,
	[IconPath] [varchar](256) NOT NULL,
	[IconName] [varchar](32) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NetIconId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NodeDetails]    Script Date: 05/09/2018 22:16:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NodeDetails](
	[DetailId] [int] IDENTITY(1,1) NOT NULL,
	[NodeObjectId] [int] NOT NULL,
	[Title] [varchar](64) NOT NULL,
	[Value] [varchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NodeGroups]    Script Date: 05/09/2018 22:16:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NodeGroups](
	[GroupId] [int] IDENTITY(1,1) NOT NULL,
	[GroupName] [varchar](64) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NodeObjects]    Script Date: 05/09/2018 22:16:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NodeObjects](
	[NodeObjectId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](32) NULL,
	[HoverText] [varchar](max) NULL,
	[xPosition] [int] NULL,
	[yPosition] [int] NULL,
	[TopologyId] [int] NOT NULL,
	[NodeGroupId] [int] NULL,
	[NetIconId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NodeObjectId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TopologyObjects]    Script Date: 05/09/2018 22:16:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TopologyObjects](
	[topologyId] [int] IDENTITY(1,1) NOT NULL,
	[siteName] [varchar](64) NOT NULL,
	[topologyDescription] [varchar](max) NULL,
	[createTime] [datetime] NOT NULL,
	[lastEditTime] [datetime] NOT NULL,
	[createdBy] [int] NOT NULL,
	[lastEditBy] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[topologyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TopologyPermissions]    Script Date: 05/09/2018 22:16:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TopologyPermissions](
	[topologyPermissionId] [int] IDENTITY(1,1) NOT NULL,
	[topologyId] [int] NOT NULL,
	[canRead] [bit] NOT NULL,
	[canWrite] [bit] NOT NULL,
	[userId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[topologyPermissionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserAttributes]    Script Date: 05/09/2018 22:16:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserAttributes](
	[AttrId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[Attribute] [varchar](10) NOT NULL,
	[Value] [varchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AttrId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserObjects]    Script Date: 05/09/2018 22:16:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserObjects](
	[userId] [int] IDENTITY(1,1) NOT NULL,
	[userName] [varchar](64) NOT NULL,
	[password] [char](74) NOT NULL,
	[forename] [varchar](64) NOT NULL,
	[surname] [varchar](64) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[userId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MediaTypes] ADD  DEFAULT ('Ethernet') FOR [Name]
GO
ALTER TABLE [dbo].[MediaTypes] ADD  DEFAULT ('#000000') FOR [Colour]
GO
ALTER TABLE [dbo].[MediaTypes] ADD  DEFAULT ((0)) FOR [Dashed]
GO
ALTER TABLE [dbo].[MediaTypes] ADD  DEFAULT ((0)) FOR [isDefault]
GO
ALTER TABLE [dbo].[NodeObjects] ADD  DEFAULT ((1)) FOR [NetIconId]
GO
ALTER TABLE [dbo].[TopologyObjects] ADD  DEFAULT (getdate()) FOR [createTime]
GO
ALTER TABLE [dbo].[TopologyObjects] ADD  DEFAULT (getdate()) FOR [lastEditTime]
GO
ALTER TABLE [dbo].[TopologyPermissions] ADD  DEFAULT ((0)) FOR [canRead]
GO
ALTER TABLE [dbo].[TopologyPermissions] ADD  DEFAULT ((0)) FOR [canWrite]
GO
USE [master]
GO
ALTER DATABASE [NetMapperIO] SET  READ_WRITE 
GO
